"""empty message

Revision ID: efc524ac56ba
Revises: 84a3a98911ed
Create Date: 2023-04-25 19:32:30.198417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc524ac56ba'
down_revision = '84a3a98911ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
