"""default users

Revision ID: 1c8042b81965
Revises: c9b67a6316a6
Create Date: 2023-04-11 20:36:10.541355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8042b81965'
down_revision = 'c9b67a6316a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
