"""create table User

Revision ID: 33398b96f04f
Revises: 1c8042b81965
Create Date: 2023-04-18 14:51:50.787165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33398b96f04f'
down_revision = '1c8042b81965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
