"""init table

Revision ID: 40601a2f70c2
Revises: 8807324d047c
Create Date: 2023-04-11 20:28:31.412725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40601a2f70c2'
down_revision = '8807324d047c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
