"""create

Revision ID: 57d3cf53f2d7
Revises: b24da1fd69d7
Create Date: 2023-04-18 15:03:31.195473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d3cf53f2d7'
down_revision = 'b24da1fd69d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
