"""init table

Revision ID: 65a2e2e30fa7
Revises: 94f452f30a29
Create Date: 2023-04-11 20:30:14.186939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a2e2e30fa7'
down_revision = '94f452f30a29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
