"""init table

Revision ID: 8b776aa854f6
Revises: 65a2e2e30fa7
Create Date: 2023-04-11 20:35:39.237909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b776aa854f6'
down_revision = '65a2e2e30fa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
