"""create tabl

Revision ID: b24da1fd69d7
Revises: 1d3709710079
Create Date: 2023-04-18 15:00:41.102193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24da1fd69d7'
down_revision = '1d3709710079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
