"""init table

Revision ID: c9b67a6316a6
Revises: 8b776aa854f6
Create Date: 2023-04-11 20:35:46.963198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b67a6316a6'
down_revision = '8b776aa854f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
