"""empty message

Revision ID: 93ab834200bf
Revises: 68e8eb8bbde9
Create Date: 2023-06-14 03:29:58.180360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ab834200bf'
down_revision = '68e8eb8bbde9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('count_likes', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('count_dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'count_dislikes')
    op.drop_column('video', 'count_likes')
    # ### end Alembic commands ###
