"""empty message

Revision ID: 68e8eb8bbde9
Revises: 65ba11d3643c
Create Date: 2023-06-14 02:18:37.256362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e8eb8bbde9'
down_revision = '65ba11d3643c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('description', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'description')
    # ### end Alembic commands ###
