"""empty message

Revision ID: b512f9e6e85f
Revises: cc4fc18322b4
Create Date: 2023-06-13 22:02:53.805060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b512f9e6e85f'
down_revision = 'cc4fc18322b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
